apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: gralnia
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: root_password
  MARIADB_DATABASE: gralnia
  MARIADB_USER: gralnia
  MARIADB_PASSWORD: gralnia_password
  DATABASE_URL: mysql+pymysql://gralnia:gralnia_password@mariadb:3306/gralnia
  API_SECRET_KEY: minikube-demo-secret
